### ISSUE TITLE
httpd-ssl.conf errors

### ISSUE THREAD

**Issue by hillbilly-mark** [l3iggs/docker-LAMP#12]
When trying to use the -v ~/sslCert:/root/sslKeys option to read my key and crt files I get the following errors:

> AH00526 Syntax error on line 143 of /etc/httpd/conf/extra httpd-ssl.conf:
> SSLCe3rtificateFile: file '/root/sslKeys/fullchain.pem does not exist or is empty.

the example shows these files as being server.crt and server.key.  I have renamed my files to match the example without luck.  The location exists with permissions as in the example.

**Comment by chris13524** [comment]
Also getting this issue. Ever figure it out?

**Comment by chris13524** [comment]
Ah, I had mounted `/root/sslKeys` which overwrote the existing keys where were generated when the image was built. Had to first copy those keys out and then mount them.

**Comment by greyltc** [comment]
sounds like you folks solved this
