### ISSUE TITLE
.httaccess doesn't work

### ISSUE THREAD

**Issue by sanzhardanybayev** [l3iggs/docker-LAMP#13]

**Comment by rodrigomanara** [comment]
try .htaccess

**Comment by aaronofleonard** [comment]
Extend the image with your own Dockerfile and add this line:

`RUN sed -i 's/AllowOverride None/AllowOverride All/' /etc/httpd/conf/httpd.conf`

Works for me!

**Comment by sanzhardanybayev** [comment]
@aaronofleonard yes! That was the problem! By default apache ignores .htaccess because of the AllowOeverride mode
