### ISSUE TITLE
Missing http user

### ISSUE THREAD

**Issue by stockmind** [l3iggs/docker-LAMP#18]
Hi, first run of the image after a while on a new server.

Launched with:
```
docker run -d -v "$CERTIFICATES":/etc/letsencrypt/live \
				 -e APACHE_ENABLE_PORT_80=true 	\
				 -e DO_SSL_LETS_ENCRYPT_FETCH=true \
				 -e EMAIL="$EMAIL" \
				 -h "$DOMAIN" \
				 -v "$WEBFOLDER":/srv/http \
				 --name "$CONTAINERNAME" \
				 -p 80:80 \
				 -p 443:443 \
				 greyltc/lamp
```

No response from ports 80 and 443 after a while.

Checked container log and got as first line: 

`AH00543: httpd: bad user name http`

Any `apachectl` command inside container returned that.

A run of `adduser http` fixed this, but the clean latest image seems to be broken atm.

**Comment by greyltc** [comment]
I'll have a look at figuring out where that user went.

**Comment by azaiter** [comment]
You replaced http user with user id 33 but wasn't replaced in httpd config file. Would that be the issue? otherwise, is the base image supposed to have the http user?

**Comment by greyltc** [comment]
The problem is that Arch has started to use systemd-sysusers to setup/generate users & groups.
A bunch are getting left out now since this container (and its parents) doesn't have systemd

**Comment by greyltc** [comment]
Okay. This is all fixed up now.
