### ISSUE TITLE
get access to phpmyadmin

### ISSUE THREAD

**Issue by dbclkclk** [l3iggs/docker-LAMP#2]
Need to get access to phpmyadmin so I can upload my schema. Any insight on this would be helpful.

**Comment by l3iggs** [comment]
Hey, sorry this is a barebones LAMP stack. I have not installed phpmyadmin here. Feel free to build a container from this one that has phpmyadmin. Some install instructions are here: https://wiki.archlinux.org/index.php/PhpMyAdmin
