### ISSUE TITLE
Add volume

### ISSUE THREAD

**Issue by fdcore** [l3iggs/docker-LAMP#6]
Add [VOLUME](https://docs.docker.com/engine/reference/builder/#volume) on **Dockerfile** for support use Volumes on **Kitematic**.

**Comment by kaloczidev** [comment]
Check out the readme's 4.th step, simply run the 
`docker run -v /parent/machine/path/to/project:/srv/http --name lamp -p 80:80 -p 443:443 -d greyltc/lamp` 
command in terminal, then the container and the attached volume is visible Kitematic. 

it works for me.

**Comment by greyltc** [comment]
sounds solved to me
