### ISSUE TITLE
Let's encrypt gets the wrong hostname

### ISSUE THREAD

**Issue by jswetzen** [l3iggs/docker-LAMP#7]
I can't get certificates from Let's encrypt because the hostname is cut off. I set it with `--hostname=my.domain.tld` and `$(hostname --fqdn)` gets it. However, `$HOSTNAME` is already set to `my` (by docker, I guess), so line 34 in `setupApacheSSLKey.sh` doesn't update it.
`: ${HOSTNAME:=$(hostname --fqdn)}`
Just changing it to
`HOSTNAME=$(hostname --fqdn)`
should do

**Comment by greyltc** [comment]
What do you mean the hostname is cut off?
Does --hostname="my.domain.tld" work?

**Comment by greyltc** [comment]
I guess @jswetzen forgot to quote his string

**Comment by jswetzen** [comment]
Hi, sorry I never answered. I wasn’t in a position to easily test quoting the hostname, so I never got around to it. But I set the HOSTNAME environment variable directly instead and that worked.
